- name: Deploy GitLab Project Application
  hosts: all
  become: true
  vars:
    app_dir: "{{ APP_DIR | default('/srv/tibava') }}"
    script_name: "{{ SCRIPT_NAME | default('/tibava') }}"
    service_name: "{{ SERVICE_NAME | default('tibava_backend.service') }}"
    analyser_host: "{{ ANALYSER_HOST | default('localhost') }}"
    analyser_port: "{{ ANALYSER_PORT | default('54051') }}"

  tasks:
    - name: Ensure the tibava group exists
      group:
        name: tibava
        state: present

    - name: Ensure the tibava user exists
      user:
        name: tibava
        group: tibava
        shell: /bin/bash
        state: present

    - name: Ensure dependencies are installed
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - acl
        state: present
        update_cache: yes

    - name: Create directory for apt keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Docker's official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker repository to Apt sources
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture | replace('x86_64', 'amd64') }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    # 5. Install Docker Engine and the Compose Plugin
    - name: Install Docker Packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Ensure user 'tibava' is in the 'docker' group
      ansible.builtin.user:
        name: tibava
        groups: docker
        append: yes
      notify: Reload systemd and restart app

    - name: Ensure target directory exists
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        owner: tibava
        group: tibava
        mode: "0755"

    - name: Pull latest code from GitLab
      ansible.builtin.git:
        repo: "https://github.com/TIBHannover/tibava.git"
        dest: "{{ app_dir }}"
        version: "feature/ansible"
        force: true
      become: true
      become_user: tibava

    - name: Copy systemd service file
      ansible.builtin.template:
        src: templates/tibava_backend.service.j2
        dest: /etc/systemd/system/{{ service_name }}
        owner: root
        group: root
        mode: "0644"
      notify: Reload systemd and restart app

    - name: Copy docker compose file
      ansible.builtin.template:
        src: templates/docker-compose.backend.yml.j2
        dest: "{{ app_dir }}/docker-compose.yml"
        owner: tibava
        group: tibava
        mode: "0644"

    - name: Copy nginx config file
      ansible.builtin.template:
        src: templates/default.conf.j2
        dest: "{{ app_dir }}/frontend/default.conf"
        owner: root
        group: root
        mode: "0644"

    - name: Copy vue app config file
      ansible.builtin.template:
        src: templates/app.config.js.j2
        dest: "{{ app_dir }}/frontend/app.config.js"
        owner: root
        group: root
        mode: "0644"

    - name: Copy vue config file
      ansible.builtin.template:
        src: templates/vue.config.js.j2
        dest: "{{ app_dir }}/frontend/vue.config.js"
        owner: root
        group: root
        mode: "0644"

    - name: Force systemd to reload config now
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Restart application service (Example)
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: restarted

    # Update Webserver and Backend
    - name: Wait for backend service to become healthy (HTTP)
      ansible.builtin.uri:
        url: "http://localhost:8000{{script_name}}/backend/healthz/readiness"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 5

    - name: Run database migration inside the backend container
      community.docker.docker_container_exec:
        container: tibava-backend-1
        command: python3 backend/src/backend/manage.py migrate
      register: exec_result

    - name: Run npm install inside the frontend container
      community.docker.docker_container_exec:
        container: tibava-frontend-1
        command: npm install
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
      register: exec_result

    - name: Run npm build inside the frontend container
      community.docker.docker_container_exec:
        container: tibava-frontend-1
        command: npm run build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
      register: exec_result

  handlers:
    - name: Reload systemd and restart app
      ansible.builtin.systemd_service:
        name: "{{ service_name }}"
        state: restarted
        daemon_reload: true
        enabled: true
