# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import analyser_pb2 as analyser__pb2

GRPC_GENERATED_VERSION = "1.71.2"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in analyser_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AnalyserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.list_plugins = channel.unary_unary(
            "/fileharbor.Analyser/list_plugins",
            request_serializer=analyser__pb2.ListPluginsRequest.SerializeToString,
            response_deserializer=analyser__pb2.ListPluginsReply.FromString,
            _registered_method=True,
        )
        self.analyse = channel.unary_unary(
            "/fileharbor.Analyser/analyse",
            request_serializer=analyser__pb2.AnalyseRequest.SerializeToString,
            response_deserializer=analyser__pb2.AnalyseReply.FromString,
            _registered_method=True,
        )


class AnalyserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def list_plugins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def analyse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AnalyserServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "list_plugins": grpc.unary_unary_rpc_method_handler(
            servicer.list_plugins,
            request_deserializer=analyser__pb2.ListPluginsRequest.FromString,
            response_serializer=analyser__pb2.ListPluginsReply.SerializeToString,
        ),
        "analyse": grpc.unary_unary_rpc_method_handler(
            servicer.analyse,
            request_deserializer=analyser__pb2.AnalyseRequest.FromString,
            response_serializer=analyser__pb2.AnalyseReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "fileharbor.Analyser", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("fileharbor.Analyser", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Analyser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def list_plugins(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fileharbor.Analyser/list_plugins",
            analyser__pb2.ListPluginsRequest.SerializeToString,
            analyser__pb2.ListPluginsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def analyse(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fileharbor.Analyser/analyse",
            analyser__pb2.AnalyseRequest.SerializeToString,
            analyser__pb2.AnalyseReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
