# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyser.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "analyser.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import data_pb2 as data__pb2
from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0e\x61nalyser.proto\x12\nfileharbor\x1a\ndata.proto\x1a\x0c\x63ommon.proto"T\n\nPluginInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12*\n\x08settings\x18\x03 \x03(\x0b\x32\x18.fileharbor.PluginConfig"\x14\n\x12ListPluginsRequest"@\n\x10ListPluginsReply\x12,\n\x0cplugin_infos\x18\x01 \x03(\x0b\x32\x16.fileharbor.PluginInfo";\n\x0e\x41nalyseRequest\x12)\n\nplugin_run\x18\x01 \x01(\x0b\x32\x15.fileharbor.PluginRun"9\n\x0c\x41nalyseReply\x12)\n\x07results\x18\x01 \x03(\x0b\x32\x18.fileharbor.PluginResult2\x9d\x01\n\x08\x41nalyser\x12N\n\x0clist_plugins\x12\x1e.fileharbor.ListPluginsRequest\x1a\x1c.fileharbor.ListPluginsReply"\x00\x12\x41\n\x07\x61nalyse\x12\x1a.fileharbor.AnalyseRequest\x1a\x18.fileharbor.AnalyseReply"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "analyser_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PLUGININFO"]._serialized_start = 56
    _globals["_PLUGININFO"]._serialized_end = 140
    _globals["_LISTPLUGINSREQUEST"]._serialized_start = 142
    _globals["_LISTPLUGINSREQUEST"]._serialized_end = 162
    _globals["_LISTPLUGINSREPLY"]._serialized_start = 164
    _globals["_LISTPLUGINSREPLY"]._serialized_end = 228
    _globals["_ANALYSEREQUEST"]._serialized_start = 230
    _globals["_ANALYSEREQUEST"]._serialized_end = 289
    _globals["_ANALYSEREPLY"]._serialized_start = 291
    _globals["_ANALYSEREPLY"]._serialized_end = 348
    _globals["_ANALYSER"]._serialized_start = 351
    _globals["_ANALYSER"]._serialized_end = 508
# @@protoc_insertion_point(module_scope)
