# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: collection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "collection.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from . import data_pb2 as data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10\x63ollection.proto\x12\nfileharbor\x1a\x0c\x63ommon.proto\x1a\ndata.proto"<\n\x0e\x43ollectionItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1e\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x10.fileharbor.Data"?\n\x0fIndexDefinition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x10\n\x08\x64istance\x18\x03 \x01(\t"V\n\rCreateRequest\x12\x17\n\x0f\x63ollection_name\x18\x01 \x01(\t\x12,\n\x07indexes\x18\x03 \x03(\x0b\x32\x1b.fileharbor.IndexDefinition"\x10\n\x0e\x43reateResponse"(\n\rDeleteRequest\x12\x17\n\x0f\x63ollection_name\x18\x01 \x01(\t"\x10\n\x0e\x44\x65leteResponse"\r\n\x0bListRequest"(\n\x0cListResponse\x12\x18\n\x10\x63ollection_names\x18\x01 \x03(\t"W\n\x10\x41\x64\x64PointsRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1e\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x10.fileharbor.Data\x12\x17\n\x0f\x63ollection_name\x18\x03 \x01(\t"E\n\x0e\x41\x64\x64PointsReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x17\n\x0findexing_job_id\x18\x03 \x01(\t"\x0e\n\x0cQueryRequest"\x0f\n\rQueryResponse"`\n\nGetRequest\x12\x17\n\x0f\x63ollection_name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x16\n\x0einclude_fields\x18\x03 \x03(\t\x12\x15\n\rinclude_media\x18\x04 \x01(\x08"9\n\x0bGetResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1e\n\x04\x64\x61ta\x18\x0c \x03(\x0b\x32\x10.fileharbor.Data2\x97\x03\n\nCollection\x12\x41\n\x06\x63reate\x12\x19.fileharbor.CreateRequest\x1a\x1a.fileharbor.CreateResponse"\x00\x12\x41\n\x06\x64\x65lete\x12\x19.fileharbor.DeleteRequest\x1a\x1a.fileharbor.DeleteResponse"\x00\x12;\n\x04list\x12\x17.fileharbor.ListRequest\x1a\x18.fileharbor.ListResponse"\x00\x12L\n\nadd_points\x12\x1c.fileharbor.AddPointsRequest\x1a\x1a.fileharbor.AddPointsReply"\x00(\x01\x30\x01\x12>\n\x05query\x12\x18.fileharbor.QueryRequest\x1a\x19.fileharbor.QueryResponse"\x00\x12\x38\n\x03get\x12\x16.fileharbor.GetRequest\x1a\x17.fileharbor.GetResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "collection_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_COLLECTIONITEM"]._serialized_start = 58
    _globals["_COLLECTIONITEM"]._serialized_end = 118
    _globals["_INDEXDEFINITION"]._serialized_start = 120
    _globals["_INDEXDEFINITION"]._serialized_end = 183
    _globals["_CREATEREQUEST"]._serialized_start = 185
    _globals["_CREATEREQUEST"]._serialized_end = 271
    _globals["_CREATERESPONSE"]._serialized_start = 273
    _globals["_CREATERESPONSE"]._serialized_end = 289
    _globals["_DELETEREQUEST"]._serialized_start = 291
    _globals["_DELETEREQUEST"]._serialized_end = 331
    _globals["_DELETERESPONSE"]._serialized_start = 333
    _globals["_DELETERESPONSE"]._serialized_end = 349
    _globals["_LISTREQUEST"]._serialized_start = 351
    _globals["_LISTREQUEST"]._serialized_end = 364
    _globals["_LISTRESPONSE"]._serialized_start = 366
    _globals["_LISTRESPONSE"]._serialized_end = 406
    _globals["_ADDPOINTSREQUEST"]._serialized_start = 408
    _globals["_ADDPOINTSREQUEST"]._serialized_end = 495
    _globals["_ADDPOINTSREPLY"]._serialized_start = 497
    _globals["_ADDPOINTSREPLY"]._serialized_end = 566
    _globals["_QUERYREQUEST"]._serialized_start = 568
    _globals["_QUERYREQUEST"]._serialized_end = 582
    _globals["_QUERYRESPONSE"]._serialized_start = 584
    _globals["_QUERYRESPONSE"]._serialized_end = 599
    _globals["_GETREQUEST"]._serialized_start = 601
    _globals["_GETREQUEST"]._serialized_end = 697
    _globals["_GETRESPONSE"]._serialized_start = 699
    _globals["_GETRESPONSE"]._serialized_end = 756
    _globals["_COLLECTION"]._serialized_start = 759
    _globals["_COLLECTION"]._serialized_end = 1166
# @@protoc_insertion_point(module_scope)
