# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import searcher_pb2 as searcher__pb2

GRPC_GENERATED_VERSION = "1.71.2"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in searcher_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SearcherStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.search = channel.unary_unary(
            "/fileharbor.Searcher/search",
            request_serializer=searcher__pb2.SearchRequest.SerializeToString,
            response_deserializer=searcher__pb2.SearchReply.FromString,
            _registered_method=True,
        )
        self.list_search_result = channel.unary_unary(
            "/fileharbor.Searcher/list_search_result",
            request_serializer=searcher__pb2.ListSearchResultRequest.SerializeToString,
            response_deserializer=searcher__pb2.ListSearchResultReply.FromString,
            _registered_method=True,
        )


class SearcherServicer(object):
    """Missing associated documentation comment in .proto file."""

    def search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def list_search_result(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SearcherServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "search": grpc.unary_unary_rpc_method_handler(
            servicer.search,
            request_deserializer=searcher__pb2.SearchRequest.FromString,
            response_serializer=searcher__pb2.SearchReply.SerializeToString,
        ),
        "list_search_result": grpc.unary_unary_rpc_method_handler(
            servicer.list_search_result,
            request_deserializer=searcher__pb2.ListSearchResultRequest.FromString,
            response_serializer=searcher__pb2.ListSearchResultReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "fileharbor.Searcher", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("fileharbor.Searcher", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Searcher(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def search(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fileharbor.Searcher/search",
            searcher__pb2.SearchRequest.SerializeToString,
            searcher__pb2.SearchReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def list_search_result(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/fileharbor.Searcher/list_search_result",
            searcher__pb2.ListSearchResultRequest.SerializeToString,
            searcher__pb2.ListSearchResultReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
