"""
Django settings for tibava project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import yaml
from pathlib import Path
from dotenv import load_dotenv
from tibava_utils import get_element


def get_value(config, env_name, config_path, default_value):
    value = get_element(config, config_path)

    if not value:
        value = default_value

    result = os.getenv(env_name, value)
    print(config, env_name, config_path, default_value, value, result, flush=True)
    return result


BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

DEFAULT_CONFIG_PATH = BASE_DIR / "backend_config.yaml"

YAML_CONFIG_PATH = os.getenv("DJANGO_CONFIG_PATH", DEFAULT_CONFIG_PATH)
with open(YAML_CONFIG_PATH, "r") as f:
    config = yaml.safe_load(f) or {}

SECRET_KEY = get_value(config, "SECRET_KEY", "secret_key", "default_secret")
DEBUG = get_value(config, "DEBUG", "debug", "False") == "True"


FORCE_SCRIPT_NAME = get_value(config, "FORCE_SCRIPT_NAME", "force_script_name", "/")

ALLOWED_HOSTS = get_value(config, "ALLOWED_HOSTS", "allowed_hosts", ["localhost"])
CSRF_TRUSTED_ORIGINS = get_value(
    config,
    "CSRF_TRUSTED_ORIGINS",
    "csrf_trusted_origins",
    ["http://localhost", "https://localhost"],
)

CORS_ORIGIN_ALLOW_ALL = (
    get_value(config, "CORS_ORIGIN_ALLOW_ALL", "cors_origin_allow_all", "True")
    == "True"
)
CORS_ALLOW_CREDENTIALS = (
    get_value(config, "CORS_ALLOW_CREDENTIALS", "cors_allow_credentials", "True")
    == "True"
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": True,
    "formatters": {
        "verbose": {
            "format": "[%(asctime)s][%(levelname)s][%(name)s.%(funcName)s:%(lineno)d] %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "backend": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "django": {"handlers": ["console"], "level": "WARNING", "propagate": False},
    },
}

INSTALLED_APPS = [
    "corsheaders",
    "backend",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

AUTH_USER_MODEL = "backend.TibavaUser"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tibava.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tibava.wsgi.application"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.memcached.PyMemcacheCache",
        "LOCATION": "memcached:11211",
        "TIMEOUT": 60 * 60 * 24,
    }
}

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "tibava",
        "USER": "postgres",
        "PASSWORD": "postgres",
        "HOST": "postgres",
        "PORT": 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/


STATICFILES_DIRS = []

STATIC_URL = FORCE_SCRIPT_NAME + "/static/"

# MEDIA_ROOT = os.path.join(os.path.dirname(__file__), "..", "media")

MEDIA_ROOT = get_value(config, "MEDIA_ROOT", "media_root", "/media/")
DATA_CACHE_ROOT = get_value(config, "DATA_CACHE_ROOT", "data_cache_root", "/cache/")
DATA_OUTPUT_PATH = get_value(
    config, "DATA_OUTPUT_PATH", "data_output_path", "/predictions"
)


GRPC_HOST = get_value(config, "ANALYSER_GRPC_HOST", "analyser.grpc_host", "analyser")
GRPC_PORT = get_value(config, "ANALYSER_GRPC_PORT", "analyser.grpc_port", 50051)

ANNOTATION_MAX_LENGTH = get_value(
    config, "ANNOTATION_MAX_LENGTH", "annotation_max_length", 1000
)

MEDIA_URL = get_value(config, "MEDIA_URL", "media_url", "/media/")
THUMBNAIL_URL = get_value(
    config, "THUMBNAIL_URL", "thumbnail_url", "http://localhost/thumbnails/"
)

# the last resolution will use for indexing
IMAGE_RESOLUTIONS = [{"min_dim": 200, "suffix": "_m"}, {"min_dim": 1080, "suffix": ""}]


USER_LIMITS_ALLOWANCE = get_value(
    config, "USER_LIMITS_ALLOWANCE", "user.limits.allowance", -1
)
USER_LIMITS_MAX_VIDEO_SIZE = get_value(
    config, "USER_LIMITS_MAX_VIDEO_SIZE", "user.limits.max_video_size", -1
)
