[project]
name = "utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "matthias springstein", email = "matthias.springstein@gmail.com" },
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
utils = "utils:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
