# Generated by Django 3.1.1 on 2023-07-31 08:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20230718_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterTimelineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cluster_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('A', 'FACE')], default='A', max_length=2)),
                ('timeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.timeline')),
            ],
        ),
    ]
