# Generated by Django 3.1.1 on 2023-08-03 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_clustertimelineitem_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustertimelineitem',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.timeline'),
        ),
    ]
