# Generated by Django 3.1.1 on 2023-08-08 13:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20230803_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('face_ref', models.UUIDField()),
                ('embedding_index', models.PositiveIntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('cti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.clustertimelineitem')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.video')),
            ],
        ),
    ]
