# Generated by Django 3.1.1 on 2023-08-23 08:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_clustertimelineitem_plugin_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustertimelineitem',
            name='type',
            field=models.CharField(choices=[('A', 'FACE'), ('P', 'PLACE')], default='A', max_length=2),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('place_ref', models.UUIDField()),
                ('embedding_index', models.PositiveIntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('image_path', models.CharField(max_length=128, null=True)),
                ('cti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.clustertimelineitem')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.video')),
            ],
        ),
    ]
