# Generated by Django 3.1.1 on 2023-12-04 20:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20230823_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelinesegment',
            options={'ordering': ['start']},
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
