# Generated by Django 3.1.1 on 2024-01-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20240122_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginrunresult',
            name='type',
            field=models.CharField(choices=[('V', 'VIDEO'), ('I', 'IMAGES'), ('S', 'SCALAR'), ('H', 'HIST'), ('SH', 'SHOTS'), ('R', 'RGB_HIST'), ('CL', 'CLUSTER'), ('FA', 'FACE'), ('E', 'IMAGE_EMBEDDINGS')], default='S', max_length=2),
        ),
    ]
