# Generated by Django 3.1.1 on 2024-01-22 20:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20240122_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plugin_item_ref', models.UUIDField()),
                ('embedding_index', models.PositiveIntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('image_path', models.CharField(max_length=128, null=True)),
                ('type', models.CharField(choices=[('A', 'FACE'), ('P', 'PLACE')], default='A', max_length=2)),
                ('cluster_timeline_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.clustertimelineitem')),
                ('plugin_run_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.pluginrunresult')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.video')),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='cti',
        ),
        migrations.RemoveField(
            model_name='place',
            name='video',
        ),
        migrations.DeleteModel(
            name='Face',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
