# Generated by Django 3.1.1 on 2024-02-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20240122_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='license',
        ),
    ]
