# Generated by Django 3.1.1 on 2024-02-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20240208_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tibavauser',
            name='allowance',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='tibavauser',
            name='max_video_size',
            field=models.BigIntegerField(default=524288000),
        ),
    ]
