# Generated by Django 3.1.1 on 2024-04-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20240213_0903_squashed_0020_auto_20240216_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='colormap_inverse',
            field=models.BooleanField(default=False),
        ),
    ]
