# Generated by Django 3.1.1 on 2024-05-06 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_remove_clusteritem_plugin_item_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysisState',
            fields=[
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.video')),
                ('selected_shots', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.timeline')),
            ],
        ),
    ]
