# Generated by Django 6.0.2 on 2026-06-03 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20240507_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginrunresult',
            name='type',
            field=models.CharField(choices=[('V', 'VIDEO'), ('I', 'IMAGES'), ('S', 'SCALAR'), ('H', 'HIST'), ('SH', 'SHOTS'), ('R', 'RGB_HIST'), ('CL', 'CLUSTER'), ('FA', 'FACE'), ('E', 'IMAGE_EMBEDDINGS'), ('B', 'TYPE_BBOXES'), ('K', 'TYPE_KPSS')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='tibavauser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
