# Generated by Django 5.2.4 on 2025-08-04 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20240507_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
