# Generated by Django 6.0.6 on 2026-06-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_pluginrunresult_type_alter_tibavauser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tibavauser',
            name='max_plugin_runs',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='tibavauser',
            name='allowance',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='tibavauser',
            name='max_video_size',
            field=models.BigIntegerField(default=-1),
        ),
    ]
